### ISSUE TITLE
GlTextureProgram don't have TextureId

### ISSUE THREAD

**Issue by digitalmidges** [natario1/Egloo#17]
Hi, I'm trying to combine CameraView and Transcoder in my app
they both working great,
but when I download the CameraView project to my app and used it as an implementation project
i got this weird bug in VideoDecoderOutput class line 60 - 

.NoSuchMethodError: No virtual method getTextureId()I in class Lcom/otaliastudios/opengl/program/GlTextureProgram; or its super classes

I've noticed when i use the libraries as implementation as describe in the docs... its working fine but the
Egloo library in the gradle external libraries is version 23... can you tell me whats going on?

**Comment by natario1** [comment]
CameraView master branch (unreleased) uses Egloo 0.4.0. Latest transcoder version uses Egloo 0.2.3. So you can either wait for a new transcoder version that uses 0.4.0, or use transcoder master branch (unreleased)

**Comment by natario1** [comment]
Now you should have an official release for both
