### ISSUE TITLE
Unable to add Egloo to the android project

### ISSUE THREAD

**Issue by alexandersokol** [natario1/Egloo#30]
Hello!

I tried to add the library to the demo android project from the current repo and got an error. It also not importing into my project. Could you please help me with it?

 I replaced 
`implementation(project(":library"))`
with 
`implementation("com.otaliastudios.opengl:egloo-android:0.5.3")`

error:
`Could not determine the dependencies of task ':app:compileDevDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:devDebugCompileClasspath'.
   > Could not resolve com.otaliastudios.opengl:egloo-android:0.5.3.
     Required by:
         project :app
      > Unable to find a matching variant of com.otaliastudios.opengl:egloo-android:0.5.3:
          - Variant 'androidJvm-releaseApiElements' capability com.otaliastudios.opengl:egloo-android:0.5.3:
              - Incompatible attribute:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Other attributes:
                  - Required cloud 'dev' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
          - Variant 'androidJvm-releaseRuntimeElements' capability com.otaliastudios.opengl:egloo-android:0.5.3:
              - Incompatible attribute:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
              - Other attributes:
                  - Required cloud 'dev' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found compatible value 'androidJvm'.
          - Variant 'metadata-api' capability com.otaliastudios.opengl:egloo-android:0.5.3:
              - Incompatible attributes:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'kotlin-metadata'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found incompatible value 'common'.
              - Other attributes:
                  - Required cloud 'dev' but no value provided.
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.
          - Variant 'metadata-commonMainMetadataElements' capability com.otaliastudios.opengl:egloo-android:0.5.3:
              - Incompatible attributes:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' and found incompatible value 'common'.
              - Other attributes:
                  - Required cloud 'dev' but no value provided.
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found org.gradle.status 'release' but wasn't required.

`

**Comment by natario1** [comment]
Can you try with implementation("com.otaliastudios.opengl:egloo:0.5.3") ?

**Comment by alexandersokol** [comment]
It works fine! Thank you!
